### ISSUE TITLE
Can plugins interact with Procon's UI / create own UI elements?

### ISSUE THREAD

**Issue by MorpheusXAUT** [phogue/Potato-Documentation#14]

**Comment by phogue** [comment]
At least Myrcon's implementation of the UI will allow plugins to essentially run like webpages. There is no default settings page or other limiting factor. Plugins are just given an empty canvas to run with.

I would imagine in the future there could be some nuget packages released that would include a boilerplate UI for plugins, but at least we start from scratch and know that a plugin can make a UI however they wish.
