### ISSUE TITLE
Can plugins perform web requests or use network connections?

### ISSUE THREAD

**Issue by MorpheusXAUT** [phogue/Potato-Documentation#16]

**Comment by phogue** [comment]
No, the sandbox is a lot more strict in Procon than it was in Procon Frostbite. The sandbox allows for code execution and disk access with varying level of permissions to some directories.

While limiting from the idea of Procon Frostbite, this actually allows for a protocol to be implemented (that will for instance connect to a Teamspeak 3 server) which can then be shared over all plugins. This will also function similarly for access to battlelog's API, just so Procon makes it easier for plugins to share information/load/connections.

The user would add a protocol connection for their Teamspeak 3 server or Battlelog, then plugins would just issue commands to that connection for any data they require.
