### ISSUE TITLE
How are database connections handled for plugins?

### ISSUE THREAD

**Issue by MorpheusXAUT** [phogue/Potato-Documentation#18]

**Comment by phogue** [comment]
Procon includes some very basic query building support that works with MySQL, SQLite and MongoDb. It's not designed to cover & do everything, but more designed to work with Procon's commands architecture and be database agnostic.

It allows for plugins to store basic information in a database, but does not allow for relational functionality. It's designed to allow for easy, persistent storage of data by a plugin which can potentially be accessed by other plugins.

There is also support for migrations which can help a plugin developer maintain a table structure over multiple releases of their plugin.
