### ISSUE TITLE
Can we get support for game “XYZ”?

### ISSUE THREAD

**Issue by MorpheusXAUT** [phogue/Potato-Documentation#21]

**Comment by phogue** [comment]
More than likely. Procon is built to support multiple protocols and I personally find implementing this to be the most rewarding aspect. We had, before a major rewrite, the codebase working in TF2 and Call of Duty: Blackops (The project is that old now..)

The intent will be to support all games. That's the fun bit for me.

**Comment by phogue** [comment]
Should also mention that it's possible others to write protocol support for Procon which can be downloaded in a similar way to plugins.

We refer to it as protocol instead of game, as we could also support Teamspeak and other services that allow external connections & commands.
