### ISSUE TITLE
Can one plugin handle multiple games or do I have to create separate releases?

### ISSUE THREAD

**Issue by MorpheusXAUT** [phogue/Potato-Documentation#9]

**Comment by phogue** [comment]
Procon from the ground up strives for protocol agnostic interface for plugins to interact with. A plugin itself should not need to know the underlying protocol to function at all.

If a plugin does require functionality of a protocol, then it really should be included in the protocol so all plugins can then benefit.

Plugins do get access to packets being sent and received, but it should be stressed that a plugin should use the commands/actions API so their plugins just seemingly work on all protocols that support the given actions.
